# Generated by Django 4.0.4 on 2022-07-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0002_alter_company_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_On_Card', models.CharField(max_length=200)),
                ('Card_Number', models.BigIntegerField()),
                ('CVC', models.BigIntegerField()),
                ('card_type', models.CharField(choices=[('visa', 'visa'), ('mastercard', 'mastercard')], max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
